# Generated by Django 4.2.5 on 2023-09-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personaldata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shippingdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Goodscategory', models.CharField(choices=[('Mobile phone', 'Mobile phone'), ('Book', 'Book'), ('Laptop', 'Laptop'), ('Tablet', 'Tablet'), ('Smart Watch', 'Smart Watch'), ('BT Speaker', 'BT Speaker')], default='Book', max_length=200)),
                ('delcity', models.CharField(max_length=100)),
                ('shippingaddr', models.CharField(max_length=500)),
                ('weight', models.IntegerField()),
            ],
        ),
    ]
