# Generated by Django 4.2.5 on 2023-09-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_personaldata_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='shippingdata',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shippingdata',
            name='Goodscategory',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fasion', 'Fasion'), ('Accessories', 'Accessories'), ('Books', 'Books'), ('Home Appliances', 'Home Appliances')], default='Book', max_length=200),
        ),
    ]
