# Generated by Django 4.2.5 on 2023-09-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_store_shippingdata_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Weight', models.FloatField()),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
