# Generated by Django 4.2.5 on 2023-09-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_couriergoods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couriergoods',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='couriergoods',
            name='Weight',
        ),
        migrations.AddField(
            model_name='couriergoods',
            name='weights',
            field=models.FloatField(null=True),
        ),
    ]
