# Generated by Django 4.2.5 on 2023-09-16 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_couriergoods_price_remove_couriergoods_weight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couriergoods',
            old_name='weights',
            new_name='Weight',
        ),
    ]
