# Generated by Django 4.2.5 on 2023-09-17 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_couriergoods_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couriergoods',
            name='product',
        ),
    ]
