# Generated by Django 4.2.5 on 2023-09-17 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_couriergoods_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingdata',
            old_name='price',
            new_name='shipvalue',
        ),
        migrations.RemoveField(
            model_name='shippingdata',
            name='weight',
        ),
    ]
