# Generated by Django 4.2.5 on 2023-09-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_goods'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourierGoods',
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
        migrations.AddField(
            model_name='shippingdata',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shippingdata',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
