# Generated by Django 4.2.5 on 2023-09-18 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0013_shippingdata_product_shippingdata_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('Status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('Order cancelled', 'Order cancelled')], default='Confirmed', max_length=200)),
                ('personaldata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.personaldata')),
                ('shippingdata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.shippingdata')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
