# Generated by Django 4.2.5 on 2023-09-27 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_rename_product_shippingdata_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='couriergoods',
            name='shiip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.shippingdata'),
        ),
    ]
