# Generated by Django 4.2.5 on 2023-09-27 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_couriergoods_shiip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='personaldata',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='shippingdata',
        ),
        migrations.AddField(
            model_name='booking',
            name='detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.couriergoods'),
        ),
    ]
